name: ovi
channels:
  - conda-forge
  - flyem-forge
  - defaults
dependencies:
  - python=3.12
  - bokeh
  - ipykernel
  - ipython
  - jupyter_core
  - jupyter_client
  - matplotlib
  - numpy
  - pandas
  - scipy
  - neuprint-python
  - pip
  - colorcet
  - colormap